{% set name = "xee" %}
{% set version = "0.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xee-{{ version }}.tar.gz
  sha256: b719e78d8e940b302c68a0c15bc37a0ea64efb6dc1499c0ff63dca5a1cdc920b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - xarray
    - earthengine-api >=0.1.374
    - pyproj
    - affine

test:
  imports:
    - xee
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/xee
  summary: A Google Earth Engine extension for Xarray.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giswqs
